name: Continuos deployment (Development)

on:
  push:
    branches:
      - dev

jobs:
  continuous_deployment:
    name: Continuos deployment (Development)
    runs-on: 	ubuntu-latest
    environment: development
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js 12.18.3
        uses: actions/setup-node@v1
        with:
          node-version: '12.18.3'
      - name: Cache yarn directory
        id: cache-yarn-dir
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-
      - name: Install dependencies
        if: steps.cache-yarn-dir.outputs.cache-hit != 'true'
        run: yarn install --production --frozen-lockfile
      - name: Build
        run: yarn build
      - name: Print Development Environment Variables
        run: printenv > .env
        env:
          NODE_ENV: development
          X_MONGO_URL: ${{ secrets.X_MONGO_URL }}
          X_MONGO_DATABASE: ${{ secrets.X_MONGO_DATABASE }}
          JWT_TOKEN_SECRET: ${{ secrets.JWT_TOKEN_SECRET }}
          JWT_TOKEN_SECRET_REFRESH: ${{ secrets.JWT_TOKEN_SECRET_REFRESH }}
      - name: Deploying Development Backend
        uses: falnyr/aws-sam-deploy-action@v1.3.0
        env:
          TEMPLATE: 'template-dev.yaml'
          AWS_STACK_NAME: 'gentem-dev-backend'
          AWS_REGION: 'us-east-1'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEPLOY_BUCKET: 'gentem-dev-backend'
          CAPABILITIES: CAPABILITY_IAM CAPABILITY_AUTO_EXPAND
