name: Continuos deployment (Production)

on:
  push:
    branches:
      - master

jobs:
  continuous_deployment:
    name: Continuos deployment (production)
    runs-on: ubuntu-18.04
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js 12.13.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.13.x'
      - name: Cache yarn directory
        id: cache-yarn-dir
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-
      - name: Install dependencies
        if: steps.cache-yarn-dir.outputs.cache-hit != 'true'
        run: yarn install --production --frozen-lockfile
      - name: Build
        run: yarn run build
      - name: Print Production Environment Variables
        run: printenv > .env
        env:
          NODE_ENV: production
          X_MONGO_URL: ${{ secrets.X_MONGO_URL }}
          X_MONGO_DATABASE: ${{ secrets.X_MONGO_DATABASE }}
          JWT_TOKEN_SECRET: ${{ secrets.JWT_TOKEN_SECRET }}
          JWT_TOKEN_SECRET_REFRESH: ${{ secrets.JWT_TOKEN_SECRET_REFRESH }}
      - name: Deploying Production Backend
        uses: falnyr/aws-sam-deploy-action@v1.0.0
        env:
          TEMPLATE: 'template-prod.yaml'
          AWS_STACK_NAME: 'gentem-prod-backend'
          AWS_REGION: 'us-east-1'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEPLOY_BUCKET: 'gentem-prod-backend'
          CAPABILITIES: CAPABILITY_IAM CAPABILITY_AUTO_EXPAND
